#!/usr/bin/env zsh

quit() {
  local bundle="${__CFBundleIdentifier:-}"
  if [[ -z $bundle ]]; then
    echo "Could not detect terminal app" >&2
    return 1
  fi
  osascript -e "do shell script \"osascript -e 'tell app id \\\"$bundle\\\" to quit' &>/dev/null &\""
}
