#!/bin/env zsh

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

setopt CORRECT
setopt CORRECT_ALL
setopt INTERACTIVE_COMMENTS

export POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
source "${HOME}/.zgen/zgen.zsh"
if ! zgen saved; then
    zgen loadall <<EOPLUGINS
        Aloxaf/fzf-tab
        romkatv/zsh-defer
        romkatv/powerlevel10k powerlevel10k
        larkery/zsh-histdb
        zsh-users/zsh-autosuggestions
        zsh-users/zsh-syntax-highlighting
EOPLUGINS
    zgen save
fi
source $HOME/dotprophet/prompt.sh
zsh-defer source $HOME/dotprophet/envvars.sh
zsh-defer source $HOME/dotprophet/aliases.sh

fpath+=~/.zfunc
zsh-defer autoload -Uz compinit && compinit
